INSERT INTO db_camunda.authority VALUES (1, 'EDITOR');
INSERT INTO db_camunda.authority VALUES (2, 'WRITER');
INSERT INTO db_camunda.authority VALUES (3, 'READER');
INSERT INTO db_camunda.authority VALUES (4, 'LECTOR');
INSERT INTO db_camunda.authority VALUES (5, 'BETAREADER');
INSERT INTO db_camunda.authority VALUES (6, 'BOARDMEMBER');

INSERT INTO db_camunda.genre VALUES (1, 'Horror');
INSERT INTO db_camunda.genre VALUES (2, 'Drama');
INSERT INTO db_camunda.genre VALUES (3, 'Thriller');
INSERT INTO db_camunda.genre VALUES (4, 'Classic');
INSERT INTO db_camunda.genre VALUES (5, 'Comic');
INSERT INTO db_camunda.genre VALUES (6, 'Detective');
INSERT INTO db_camunda.genre VALUES (7, 'Mystery');

INSERT INTO db_camunda.user VALUES ('READER', '1', 'Beograd', 'radebp@gmail.com', 'Jovan', 'Jovic', '$2a$10$pkor3weNtry8mHqwHCmSgOVJBJfsmUHKxXR6RfiULsGPcsIT.2B.2', 'Srbija', 'reader1');
INSERT INTO db_camunda.user VALUES ('READER', '2', 'Beograd', 'ooo@gmail.com', 'Milica', 'Petrovic', '$2a$10$pkor3weNtry8mHqwHCmSgOVJBJfsmUHKxXR6RfiULsGPcsIT.2B.2', 'Srbija', 'reader2');
INSERT INTO db_camunda.user VALUES ('WRITER', '3', 'Novi Sad', 'jekibp@gmail.com', 'Milovan', 'Nikolic', '$2a$10$pkor3weNtry8mHqwHCmSgOVJBJfsmUHKxXR6RfiULsGPcsIT.2B.2', 'Srbija', 'writer1');
INSERT INTO db_camunda.user VALUES ('WRITER', '4', 'Nis', 'teodora@gmail.com', 'Teodora', 'Plavsic', '$2a$10$pkor3weNtry8mHqwHCmSgOVJBJfsmUHKxXR6RfiULsGPcsIT.2B.2', 'Srbija', 'writer2');
INSERT INTO db_camunda.user VALUES ('EDITOR', '5', 'Banja Luka', 'petar.curcin97@gmail.com', 'Uros', 'Novakovic', '$2a$10$pkor3weNtry8mHqwHCmSgOVJBJfsmUHKxXR6RfiULsGPcsIT.2B.2', 'Bosna', 'editor1');
INSERT INTO db_camunda.user VALUES ('EDITOR', '6', 'Beograd', 'mejl@gmail.com', 'Ivana', 'Mirkovic', '$2a$10$pkor3weNtry8mHqwHCmSgOVJBJfsmUHKxXR6RfiULsGPcsIT.2B.2', 'Srbija', 'editor2');
INSERT INTO db_camunda.user VALUES ('EDITOR', '7', 'Beograd', 'mejl2@gmail.com', 'Milos', 'Markovic', '$2a$10$pkor3weNtry8mHqwHCmSgOVJBJfsmUHKxXR6RfiULsGPcsIT.2B.2', 'Srbija', 'editor3');
INSERT INTO db_camunda.user VALUES ('EDITOR', '8', 'Beograd', 'mejl3@gmail.com', 'Dragana', 'Kljajic', '$2a$10$pkor3weNtry8mHqwHCmSgOVJBJfsmUHKxXR6RfiULsGPcsIT.2B.2', 'Srbija', 'editor4');
INSERT INTO db_camunda.user VALUES ('LECTOR', '9', 'Beograd', 'stojakovic.e2110.2020@uns.ac.rs.com', 'Nemanja', 'Milic', '$2a$10$pkor3weNtry8mHqwHCmSgOVJBJfsmUHKxXR6RfiULsGPcsIT.2B.2', 'Srbija', 'lector1');
INSERT INTO db_camunda.user VALUES ('BETAREADER', '10', 'Loznica', 'fojkars@gmail.com', 'Isidora', 'Savic', '$2a$10$pkor3weNtry8mHqwHCmSgOVJBJfsmUHKxXR6RfiULsGPcsIT.2B.2', 'Srbija', 'betareader1');
INSERT INTO db_camunda.user VALUES ('BETAREADER', '11', 'Vranje', 'urospop97@gmail.com', 'Dragana', 'Karanovic', '$2a$10$pkor3weNtry8mHqwHCmSgOVJBJfsmUHKxXR6RfiULsGPcsIT.2B.2', 'Srbija', 'betareader2');
INSERT INTO db_camunda.user VALUES ('BOARDMEMBER', '12', 'Vranje', 'mmm@gmail.com', 'Ljubica', 'Maric', '$2a$10$pkor3weNtry8mHqwHCmSgOVJBJfsmUHKxXR6RfiULsGPcsIT.2B.2', 'Srbija', 'boardMember1');
INSERT INTO db_camunda.user VALUES ('BOARDMEMBER', '13', 'Prokuplje', 'mmm2@gmail.com', 'Djordje', 'Jovanovic', '$2a$10$pkor3weNtry8mHqwHCmSgOVJBJfsmUHKxXR6RfiULsGPcsIT.2B.2', 'Srbija', 'boardMember2');
INSERT INTO db_camunda.user VALUES ('BOARDMEMBER', '14', 'Kraljevo', 'mmm3@gmail.com', 'Dragana', 'Karanovic', '$2a$10$pkor3weNtry8mHqwHCmSgOVJBJfsmUHKxXR6RfiULsGPcsIT.2B.2', 'Srbija', 'boardMember3');

INSERT INTO db_camunda.user_authority values (1,3);
INSERT INTO db_camunda.user_authority values (2,3);
INSERT INTO db_camunda.user_authority values (3,2);
INSERT INTO db_camunda.user_authority values (4,2);
INSERT INTO db_camunda.user_authority values (5,1);
INSERT INTO db_camunda.user_authority values (6,1);
INSERT INTO db_camunda.user_authority values (7,1);
INSERT INTO db_camunda.user_authority values (8,1);
INSERT INTO db_camunda.user_authority values (9,4);
INSERT INTO db_camunda.user_authority values (10,5);
INSERT INTO db_camunda.user_authority values (11,5);
INSERT INTO db_camunda.user_authority values (12,6);
INSERT INTO db_camunda.user_authority values (13,6);
INSERT INTO db_camunda.user_authority values (14,6);
